# имя, которое будет показано в интерфейсе github.com
name: Tel_bot_news
# список событий, при которых будут запускаться задания
on:
  # Чтобы вручную запустить рабочий процесс
  workflow_dispatch:
  # чтобы он запускался каждый день недели в 7:00 по Гринвичу
  schedule:
    - cron: '20 8 * * *'

# одно или несколько заданий, которые могут быть запущены параллельно или последовательно
jobs:
 # у этого workflow всего одна задача single
  single:
    runs-on: ubuntu-latest
    # шаги задания запускаются последовательно
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # запуск одной shell-команды
      - name: Run step one
        run: echo "Single job, step one, single command"

      # запуск двух shell-команд
      - name: Run step two
        run: |
          echo "Single job, step two, command one"
          echo "Single job, step two, command two"
