# имя, которое будет показано в интерфейсе github.com
name: Tel_bot_news
# список событий, при которых будут запускаться задания
on:
  # Чтобы вручную запустить рабочий процесс
  workflow_dispatch:
  # чтобы он запускался каждый день недели в 6:40 по Москве (+3 ч)
  schedule:
    - cron: '40 3 * * *'

# одно или несколько заданий, которые могут быть запущены параллельно или последовательно
jobs:
 # у этого workflow всего одна задача single
  single:
    runs-on: ubuntu-latest
    # шаги задания запускаются последовательно
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 20
          cache: 'npm'  
      - name: Install dependencies 
        run: npm install 
      - name: Run script 
        run: node gh.js 
      # запуск одной shell-команды
      - name: Run step one
        run: echo "Single job, step one, single command"

     
